(define (problem merchant)
(:domain vincentland)
(:objects daughter field troll hammer blacksmith ore shop wolf lumberjack cave secret you baker king village castle gel wheat fireball forest bakery guard slime sword pelt spellbook forge merchant )
(:init (has field wheat)
(at king field)
(character daughter)
(weapon sword)
(has king secret)
(has castle spellbook)
(adjacent village field)
(adjacent village forge)
(adjacent field cave)
(character blacksmith)
(item ore)
(has troll hammer)
(has cave ore)
(character guard)
(at daughter cave)
(information secret)
(location forest)
(adjacent castle village)
(at slime village)
(at merchant shop)
(location forge)
(at guard shop)
(item hammer)
(item gel)
(character lumberjack)
(monster wolf)
(= (total-cost) 0)
(has you fireball)
(weapon hammer)
(location cave)
(location castle)
(location shop)
(item sword)
(has spellbook fireball)
(item spellbook)
(adjacent village bakery)
(character baker)
(character king)
(item pelt)
(has king fireball)
(at blacksmith forge)
(has you sword)
(cooperative baker)
(location village)
(at baker bakery)
(location bakery)
(at wolf village)
(has slime gel)
(adjacent village shop)
(character merchant)
(has blacksmith hammer)
(captive troll daughter)
(information fireball)
(location field)
(has wolf pelt)
(monster slime)
(adjacent village forest)
(player you)
(at lumberjack village)
(at you field)
(item wheat)
(at troll village)
(monster troll)
)
(:goal (and (experimented hammer) (damaged sword)))
(:metric minimize (total-cost)))