(define (domain metricVehicle)
    (:requirements :strips :fluents)
    (:predicates 
        (vehicle ?v)
        (location ?p)
        (at ?v ?p)
        (accessible ?v ?p1 ?p2))
    (:functions 
        (fuel-level ?v)
        (fuel-used ?v)
        (fuel-required ?p1 ?p2)
        (total-fuel-used))
    (:action drive
        :parameters (?v ?from ?to)
        :precondition (and (at ?v ?from)
            (vehicle ?v)
            (location ?from)
            (location ?to)
            (accessible ?v ?from ?to)
            (>= (fuel-level ?v) (fuel-required ?from ?to)))
        :effect (and (not (at ?v ?from))
            (at ?v ?to)
            (decrease (fuel-level ?v) (fuel-required ?from ?to))
            (increase (total-fuel-used) (fuel-required ?from ?to))
            (increase (fuel-used ?v) (fuel-required ?from ?to)))
    )
)
