(define (problem blacksmith)
(:domain vincentland)
(:objects ore wheat field troll mine baker hammer bakery forge you blacksmith )
(:init (item wheat)
(item hammer)
(at blacksmith forge)
(at troll mine)
(at you bakery)
(cooperative blacksmith)(player you)
(at baker bakery)
(item ore)
(has mine ore)
(character troll)
(weapon hammer)
(character blacksmith)
(location bakery)
(has field wheat)
(location mine)
(character baker)
(has troll hammer)
(location field)
(has blacksmith ore)
(location forge)
)
(:goal (and (character blacksmith) (has blacksmith wheat) (at troll mine))))