(define (problem blacksmith)
    (:domain vincentland)
    (:objects blacksmith you ore mine forge bakery camp)
    (:init (location mine)
          (character blacksmith)
          (location forge)
          (location bakery)
          (location camp)
          (item ore)
          (has mine ore)
          (at blacksmith forge)
          (player you)
          (at you bakery))

    (:goal (and (has blacksmith ore)
            (at blacksmith forge)))
)