(define (problem lumberjack)
(:domain vincentland)
(:objects slime hammer pelt wheat you wolf king lumberjack fireball baker sword guard castle troll forge forest secret field daughter blacksmith spellbook merchant ore shop gel bakery cave village )
(:init (location forest)
(has king secret)
(item hammer)
(weapon sword)
(at you bakery)
(character merchant)
(character baker)
(item wheat)
(has blacksmith ore)
(character king)
(item gel)
(item spellbook)
(has guard sword)
(monster slime)
(adjacent village forest)
(has field wheat)
(at wolf forest)
(at lumberjack village)
(at troll cave)
(location field)
(location castle)
(location cave)
(monster wolf)
(location village)
(has wolf pelt)
(adjacent village bakery)
(location forge)
(has troll hammer)
(player you)
(item pelt)
(at slime field)
(adjacent village forge)
(character guard)
(location shop)
(= (total-cost) 0)
(weapon hammer)
(adjacent field cave)
(information secret)
(character blacksmith)
(has slime gel)
(at king castle)
(at guard village)
(at daughter cave)
(captive troll daughter)
(item ore)
(location bakery)
(monster troll)
(at baker bakery)
(has castle spellbook)
(cooperative blacksmith)
(adjacent village field)
(character lumberjack)
(information fireball)
(adjacent village shop)
(item sword)
(has spellbook fireball)
(adjacent castle village)
(at blacksmith forge)
(has cave ore)
(character daughter)
(at merchant shop)
)
(:goal (and (damaged spellbook) (dead slime)))
(:metric minimize (total-cost)))