(define (problem baker)
    (:domain vincentland)
    (:objects baker you wheat field bakery forge camp)
    (:init (location field)
          (character baker)
          (location forge)
          (location bakery)
          (location camp)
          (item wheat)
          (has field wheat)
          (at baker bakery)
          (player you)
          (at you bakery))

    (:goal (and (has baker wheat)
            (at baker bakery)))
)